FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=target/vanguardia-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} vanguardia-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/vanguardia-0.0.1-SNAPSHOT.jar"]
